### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by jeffslofish** [alexcpendleton/sleep-tight#16]
If I follow the directions and do a `npm run dev` after `npm run hot` in a different terminal then nothing seems to happen and if I browse to http://localhost:8080, it's just a blank page.

If I run `npm run prod`, then I get the following error:

App threw an error during load
Error: Cannot find module './js/core/mainThreadReceiver.js'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/jeff/sleep-tight/source/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jeff/sleep-tight/source/app/build/app.js:10:28)
    at Object.<anonymous> (/Users/jeff/sleep-tight/source/app/build/app.js:89:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

(sorry no easy pull request for this one, at this time!)

**Comment by alexcpendleton** [comment]
Fixed
